# Generated by Django 5.1.2 on 2024-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='table_resevation',
            field=models.BooleanField(default=True, verbose_name='使用されているか'),
        ),
    ]
