# Generated by Django 4.2.6 on 2024-11-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception_system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seat",
            old_name="teble_number",
            new_name="table_number",
        ),
        migrations.AddField(
            model_name="seat",
            name="table_connect",
            field=models.BooleanField(default=1, verbose_name="連結有、無"),
            preserve_default=False,
        ),
    ]
