# Generated by Django 4.2.6 on 2024-11-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="table_connect",
            field=models.BooleanField(default=2, verbose_name="連結有、無"),
            preserve_default=False,
        ),
    ]
