# Generated by Django 5.1.2 on 2025-01-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='table_type',
            field=models.IntegerField(choices=[(0, 'カウンター'), (1, 'テーブル'), (2, 'ソファー')], default=0, verbose_name='座席種別'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='table_type',
            field=models.IntegerField(choices=[(0, 'カウンター'), (1, 'テーブル'), (2, 'ソファー')], verbose_name='座席種別'),
        ),
    ]
