# Generated by Django 5.1.2 on 2025-01-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='利用終了時間'),
        ),
    ]
