# Generated by Django 4.2.6 on 2024-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="clean",
        ),
        migrations.AddField(
            model_name="seat",
            name="clean_status",
            field=models.BooleanField(default=False, verbose_name="清掃済、未"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="electrical_outlet",
            field=models.BooleanField(default=False, verbose_name="コンセント有、無"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="table_connect",
            field=models.BooleanField(default=False, verbose_name="連結有、無"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="table_resevation",
            field=models.BooleanField(default=False, verbose_name="使用されているか"),
        ),
    ]
