# Generated by Django 5.1.2 on 2024-11-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_system', '0002_alter_seat_table_resevation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='clean',
            new_name='clean_status',
        ),
        migrations.AlterField(
            model_name='seat',
            name='table_resevation',
            field=models.BooleanField(default=False, verbose_name='使用されているか'),
        ),
    ]
