# Generated by Django 4.2.6 on 2024-11-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reception_system", "0002_seat_table_connect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="table_connect",
        ),
    ]
