# Generated by Django 5.1.2 on 2025-02-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception_system', '0002_alter_reception_table_type_alter_seat_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='seat',
        ),
        migrations.AddField(
            model_name='reception',
            name='seat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_seat1', to='reception_system.seat'),
        ),
        migrations.AddField(
            model_name='reception',
            name='seat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_seat2', to='reception_system.seat'),
        ),
    ]
