# Generated by Django 4.2.6 on 2024-11-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception_system", "0005_alter_reception_reception_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="conditions",
            field=models.CharField(max_length=100, verbose_name="条件"),
        ),
    ]
