# Generated by Django 4.2.6 on 2024-11-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception_system", "0006_alter_reception_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="table_connect",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="table_reservation",
        ),
        migrations.AddField(
            model_name="seat",
            name="table_resevation",
            field=models.BooleanField(default=1, verbose_name="使用されているか"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reception",
            name="conditions",
            field=models.CharField(max_length=100, null=True, verbose_name="条件"),
        ),
        migrations.AlterField(
            model_name="reception",
            name="reception_time",
            field=models.DateTimeField(null=True, verbose_name="利用開始時間"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="clean",
            field=models.BooleanField(null=True, verbose_name="清掃済、未"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="electrical_outlet",
            field=models.BooleanField(null=True, verbose_name="コンセント有、無"),
        ),
    ]
